### ISSUE TITLE
peer to peer code  code review

### ISSUE THREAD

**Issue by CELYNEBIRUNGI** [sadaf-Daneshgar/Leaderboard#2]
Hi@Sadaf,
 your work is amazing!  Great job at implementing all necessary requirements. there are issues with your code
![unnamed](https://github.com/sadaf-Daneshgar/Leaderboard/assets/113887926/36098d1e-3412-4df2-8c2c-8750df7888fb)

**Comment by sadaf-Daneshgar** [comment]
@CELYNEBIRUNGI 👋
 Thank you!
